---
editUrl: false
next: false
prev: false
title: "AssertionError"
---

Defined in: core/build/general/Error.d.ts:11

Thrown when a descriptor assertion fails

## Extends

- `Error`

## Constructors

### Constructor

> **new AssertionError**(`errors`): `AssertionError`

Defined in: core/build/general/Error.d.ts:13

#### Parameters

##### errors

[`MetadataError`](/reference/dpkit/metadataerror/)[]

#### Returns

`AssertionError`

#### Overrides

`Error.constructor`

## Properties

### cause?

> `optional` **cause**: `unknown`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es2022.error.d.ts:26

#### Inherited from

`Error.cause`

***

### errors

> `readonly` **errors**: [`MetadataError`](/reference/dpkit/metadataerror/)[]

Defined in: core/build/general/Error.d.ts:12

***

### message

> **message**: `string`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1077

#### Inherited from

`Error.message`

***

### name

> **name**: `string`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

`Error.name`

***

### stack?

> `optional` **stack**: `string`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1078

#### Inherited from

`Error.stack`
